apiVersion: v1
kind: Service
metadata:
  name: argo-server
  namespace: argo
  labels:
    app: argo-server
spec:
  type: NodePort
  ports:
  - port: 2746
    targetPort: 2746
    protocol: TCP
  selector:
    app: argo-server

