name: CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Set up Golang
      uses: actions/setup-go@v1
      with:
        go-version: 1.12.9
      id: go
    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
    - name: Format
      run: |
        GO111MODULE=off GOBIN=/usr/local/bin go get golang.org/x/tools/cmd/goimports
        make fmt

